#!/bin/bash

mkdir -p out

cp biblio/references.bib references.bib

docker run --rm \
  --workdir='/root/' \
  -v `pwd`/paper.tex:/root/paper.tex \
  -v `pwd`/references.bib:/root/references.bib \
  -v `pwd`/sections:/root/sections \
  -v `pwd`/figures:/root/figures \
  -v `pwd`/.deps/acmart.cls:/root/acmart.cls \
  -v `pwd`/.deps/ACM-Reference-Format.bst:/root/ACM-Reference-Format.bst \
  -v `pwd`/out:/root/out \
  tianon/latex sh -c \
    "pdflatex paper &&
     bibtex paper &&
     pdflatex paper &&
     pdflatex paper &&
     mv paper.pdf /root/out/" &> build.log
    

if [ $? != "0" ] ; then
  echo "ERROR"
  cat build.log
  rm build.log
  exit 1
fi

mv out/paper.pdf .
rm -r out
rm build.log

exit 0
